### ISSUE TITLE
[FORGE] Possible incompatibility with Apotheosis

### ISSUE THREAD

**Issue by doemty** [ZsoltMolnarrr/Wizards#58]
![image](https://github.com/user-attachments/assets/a1fbbe47-594c-4e5e-bb7b-97b7874086ad)
ZsoltMolnarrr, I am really sorry if I annoy you. I wanted to show the questionable case (maybe a problem) with Apotheosis'es affixes.
I mean this fire damage bonus from Apotheosis doesn't work and Apotheosis use sword's affixes (so there is more sense to use staves and wands as swords), I think it's a problem. I thought that staves and wands were in sword's tag, but no.
P.S.: Also check issues with Curious plzz

**Comment by ZsoltMolnarrr** [comment]
I am not familiar with Apotheosis.

Anyone looking for compatibility between Spell Power Attributes and Apotheosis is free to do so, since Spell Power Attributes mod has been offering a dedicated API for such purposes.

Putting staves and wands into sword tag would be a semantical error, anyone wishing to do so, is free to do it with a custom datapack.

**Comment by doemty** [comment]
> I am not familiar with Apotheosis.
> 
> Anyone looking for compatibility between Spell Power Attributes and Apotheosis is free to do so, since Spell Power Attributes mod has been offering a dedicated API for such purposes.
> 
> Putting staves and wands into sword tag would be a semantical error, anyone wishing to do so, is free to do it with a custom datapack.

So if I make a custom tag it would work? Thx!
