### ISSUE TITLE
1.18 port? 

### ISSUE THREAD

**Issue by zack-zzq** [ZsoltMolnarrr/Wizards#7]
Do you have a plan to port to 1.18?

**Comment by ZsoltMolnarrr** [comment]
Will not happen. Discord pinned message:

Hello everyone,
People looking for answers on Forge port and different game versions, here is my current stance.

Game versions
- 1.19.3 - will be coming as soon as the project moves out of beta stage
- 1.18.2 - Statistically irrelevant on Fabric (5-10% of the users) -> will not be backported for Fabric 1.18.2
- 1.16.X - Nope

Forge
- Forge compatibility for all of my previous mods burnt up lots of development time, at such a high rate, I can no longer justify. I am only human, doing this as hobby, my development capacity is limited. Please understand that the engine of this project is massive and complex.
- Players using Forge tend to report much more issues then Fabric users, (this is not fault of players, but rather the messy ecosystem of Forge), resulting lots of time burnt on handling user reports.
- Would require backporting to at least 1.18.2 since Forge users tend to use older versions

Summary: Comatibility is expensive + Players flooding with problems + backporting required -> I have no capacity for this right now.
Forge might get support in the future, but cannot say when.

Also to people asking for more and more versions and variants: please rationalize your expectations towards a singular developer doing this as a hobby.
